CREATE TABLE PACK_GRADES(
    GRADE_ID int,
    GRADE_NAME varchar2(25),
    MIN_PRICE int,
    MAX_PRICE int)
	
INSERT INTO PACK_GRADES VALUES (1, 'Very Low', 0, 10);
INSERT INTO PACK_GRADES VALUES (2, 'Low', 11, 20);
INSERT INTO PACK_GRADES VALUES (3, 'Medium', 21, 40);
INSERT INTO PACK_GRADES VALUES (4, 'High', 41, 80);
INSERT INTO PACK_GRADES VALUES (5, 'Very High', 81, 150);

ALTER TABLE "PACK_GRADES" ADD CONSTRAINT "GRADE_ID_PK" PRIMARY KEY ("GRADE_ID");